name: GitHub Packages Registry

published: true

images:
  api:
    dockerfile: ./vizolabs-api/Dockerfile
    context: .
    destination: ghcr.io/vizolabs/vizotranslator-api:latest

  web:
    dockerfile: ./vizolabs-web/Dockerfile
    context: .
    destination: ghcr.io/vizolabs/vizotranslator-web:latest
